language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

dist: xenial

addons:
  chrome: stable
  sauce_connect: true

env:
  - WR_TEST=no
  - WR_TEST=yes

services: xvfb

cache:
  directories:
    - node_modules

sudo: required

install:
  - ./.travis/install.sh

before_install:
  - 'if [ "$WR_TEST" = "yes" ]; then sudo sysctl kernel.unprivileged_userns_clone=1; fi'

script:
  - ./.travis/test.sh

after_success:
  - codecov

matrix:
  include:
   - name: "py37 windows"
        os: windows
        language: shell
        before_install:
          - choco install python --version 3.7.7
          - python --version
          - python -m pip install --upgrade pip
          - pip3 install --upgrade pytest
          - pip3 install codecov
        env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

  allow_failures:
    - env: WR_TEST=yes
    - python: "2.7"

  exclude:
    - env: WR_TEST=yes
      python: "2.7"
    - env: WR_TEST=yes
      python: "3.5"
    - env: WR_TEST=yes
      python: "3.7"

